function createFigureTrainingTime(X1, YMatrix1, filename)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 24-Aug-2020 23:48:03

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.108333333333333 0.120726495726496 0.856770833333333 0.86645299145299]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'DisplayName','GRU-NN','Marker','square','LineWidth',4);
set(plot1(2),'DisplayName','CNN','Marker','o','LineWidth',3,...
    'LineStyle','-.');

% Create light
light('Parent',axes1,...
    'Position',[-0.999998479586801 0.00020207228698253 0.00173204817413597]);

% Create ylabel
ylabel({'Mean training time per epoch','(Seconds)'},'FontWeight','bold');

% Create xlabel
xlabel({'Number of IQ samples'},'FontWeight','bold');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',24,'FontWeight','bold','GridAlpha',0.45,...
    'MinorGridAlpha',0.45,'SortMethod','childorder','XMinorGrid','on',...
    'YMinorGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.847712419876535 0.503514835939419 0.116536460320155 0.112847224769429],...
    'FontSize',24);



filename = string(filename)+"_training_time";
export_fig(filename, '-a1', '-pdf', '-transparent');